import 'server-only';
import {db} from '@/lib/db';
import {Repository} from '@/lib/repository';
import {AppController} from './app.controller';
import {AppService} from './app.service';
import {AssuranceSubmissionsController} from './assurance-submissions/assurance-submissions.controller';
import {AssuranceSubmissionsService} from './assurance-submissions/assurance-submissions.service';
import {AssuranceTicketsController} from './assurance-tickets/assurance-tickets.controller';
import {AssuranceTicketsService} from './assurance-tickets/assurance-tickets.service';
import {AttachmentsController} from './attachments/attachments.controller';
import {Attachment} from './attachments/attachments.entity';
import {AttachmentsService} from './attachments/attachments.service';
import {AuditLogsController} from './audit-logs/audit-logs.controller';
import {AuditLog} from './audit-logs/audit-logs.entity';
import {AuditLogsService} from './audit-logs/audit-logs.service';
import {BusinessRulesService} from './business-rules/business-rules.service';
import {CpeInventoryController} from './cpe-inventory/cpe-inventory.controller';
import {CpeInventory} from './cpe-inventory/cpe-inventory.entity';
import {CpeInventoryService} from './cpe-inventory/cpe-inventory.service';
import {CpeReplacementsController} from './cpe-replacements/cpe-replacements.controller';
import {CpeReplacement} from './cpe-replacements/cpe-replacements.entity';
import {CpeReplacementsService} from './cpe-replacements/cpe-replacements.service';
import {DeliverySubmissionsController} from './delivery-submissions/delivery-submissions.controller';
import {DeliverySubmission} from './delivery-submissions/delivery-submissions.entity';
import {DeliverySubmissionsService} from './delivery-submissions/delivery-submissions.service';
import {EquipmentController} from './equipment/equipment.controller';
import {LogisticsController} from './legacy-aolms/logistics/logistics.controller';
import {LogisticsService} from './legacy-aolms/logistics/logistics.service';
import {OperationsDatabase} from './legacy-aolms/operations-database';
import {ServiceDeliveryController} from './legacy-aolms/service-delivery/service-delivery.controller';
import {ServiceDeliveryService} from './legacy-aolms/service-delivery/service-delivery.service';
import {StaffController} from './legacy-aolms/staff/staff.controller';
import {StaffService} from './legacy-aolms/staff/staff.service';
import {OntInventoryController} from './ont-inventory/ont-inventory.controller';
import {OntInventory} from './ont-inventory/ont-inventory.entity';
import {OntInventoryService} from './ont-inventory/ont-inventory.service';
import {OrderAssignmentsController} from './order-assignments/order-assignments.controller';
import {OrderAssignment} from './order-assignments/order-assignments.entity';
import {OrderAssignmentsService} from './order-assignments/order-assignments.service';
import {OrdersController} from './orders/orders.controller';
import {Order} from './orders/orders.entity';
import {OrdersService} from './orders/orders.service';
import {ProfilesController} from './profiles/profiles.controller';
import {Profile} from './profiles/profiles.entity';
import {ProfilesService} from './profiles/profiles.service';
import {ProjectAuditService} from './project-audit/project-audit.module';
import {ProjectAuditController} from './project-audit/project-audit.module';
import {ProjectsController} from './projects/projects.controller';
import {Project} from './projects/projects.entity';
import {ProjectsService} from './projects/projects.service';
import {SupabaseService} from './supabase/supabase.service';

export const getAppController = () => new AppController(getAppService());
export const getAppService = () => new AppService();
export const getAssuranceSubmissionsController = () => new AssuranceSubmissionsController(getAssuranceSubmissionsService());
export const getAssuranceSubmissionsService = () => new AssuranceSubmissionsService(db);
export const getAssuranceTicketsController = () => new AssuranceTicketsController(getAssuranceTicketsService());
export const getAssuranceTicketsService = () => new AssuranceTicketsService(db);
export const getAttachmentsController = () => new AttachmentsController(getAttachmentsService());
export const getAttachmentsService = () => new AttachmentsService(new Repository<Attachment>('attachments',["id","submission_id","submission_type","file_name","storage_path","file_type","file_size","uploaded_by","created_at"]));
export const getAuditLogsController = () => new AuditLogsController(getAuditLogsService());
export const getAuditLogsService = () => new AuditLogsService(new Repository<AuditLog>('audit_logs',["id","user_id","table_name","record_id","action","old_values","new_values","created_at"]));
export const getBusinessRulesService = () => new BusinessRulesService();
export const getCpeInventoryController = () => new CpeInventoryController(getCpeInventoryService());
export const getCpeInventoryService = () => new CpeInventoryService(new Repository<CpeInventory>('cpe_inventory',["id","project_id","order_number","installation_date","exchange","block","road","building","flat","asset_description","quantity","po_number","serial_number","contractor","connection_type","lo_name","labor_charge","cpe_charge","source_year","source_sheet","created_at","updated_at"]));
export const getCpeReplacementsController = () => new CpeReplacementsController(getCpeReplacementsService());
export const getCpeReplacementsService = () => new CpeReplacementsService(new Repository<CpeReplacement>('cpe_replacements',["id","submission_id","submission_type","old_cpe_model","old_cpe_serial","new_cpe_model","new_cpe_serial","reason","created_at"]));
export const getDeliverySubmissionsController = () => new DeliverySubmissionsController(getDeliverySubmissionsService());
export const getDeliverySubmissionsService = () => new DeliverySubmissionsService(new Repository<DeliverySubmission>('delivery_submissions',["response_order_type","response_connection_type","id","order_id","technician_id","status","last_saved_at","submitted_at","edit_deadline","actioned","sub_root_cause","item_category","ont_protection","internal_wiring","actual_actioned_item","actual_actioned_sub_item","cable_type","cable_length","conduit_clearance","conduit_pipe","pvc_trunk","total_conduit","mims_sn","nce_sn","ap1_sn","ap2_sn","ap3_sn","ap4_sn","retrieved_cpe","remarks","created_at","updated_at"]),getBusinessRulesService());
export const getEquipmentController = () => new EquipmentController(db);
export const getLogisticsController = () => new LogisticsController(getLogisticsService());
export const getLogisticsService = () => new LogisticsService(getOperationsDatabase());
export const getOperationsDatabase = () => new OperationsDatabase(db);
export const getServiceDeliveryController = () => new ServiceDeliveryController(getServiceDeliveryService());
export const getServiceDeliveryService = () => new ServiceDeliveryService(getOperationsDatabase());
export const getStaffController = () => new StaffController(getStaffService());
export const getStaffService = () => new StaffService(getOperationsDatabase());
export const getOntInventoryController = () => new OntInventoryController(getOntInventoryService());
export const getOntInventoryService = () => new OntInventoryService(new Repository<OntInventory>('ont_inventory',["id","item_code","receiving_date","reservation_number","serial_number","quantity","model","po_number","ont_type","source_sheet","status","created_at","updated_at"]));
export const getOrderAssignmentsController = () => new OrderAssignmentsController(getOrderAssignmentsService());
export const getOrderAssignmentsService = () => new OrderAssignmentsService(new Repository<OrderAssignment>('order_assignments',["id","order_id","technician_id","assigned_by","assignment_status","assigned_at","completed_at","created_at","updated_at"]));
export const getOrdersController = () => new OrdersController(getOrdersService());
export const getOrdersService = () => new OrdersService(new Repository<Order>('orders',["id","project_id","work_date","team","exchange","order_number","contact","lo","service_identifier","order_type","block","road","building","flat","slot","package","cpr_cr","controller_remarks","appointment","task_created_at","order_created_at","connection_type","fttr_type","action","sub_root_cause","item_category","technician_id","created_by","created_at","updated_at"]),new Repository<Profile>('profiles',["id","employee_code","full_name","email","role","is_active","created_at","updated_at"]),new Repository<OrderAssignment>('order_assignments',["id","order_id","technician_id","assigned_by","assignment_status","assigned_at","completed_at","created_at","updated_at"]),getProfilesService());
export const getProfilesController = () => new ProfilesController(getProfilesService());
export const getProfilesService = () => new ProfilesService(new Repository<Profile>('profiles',["id","employee_code","full_name","email","role","is_active","created_at","updated_at"]),getSupabaseService());
export const getProjectAuditService = () => new ProjectAuditService(getOperationsDatabase());
export const getProjectAuditController = () => new ProjectAuditController(getProjectAuditService());
export const getProjectsController = () => new ProjectsController(getProjectsService());
export const getProjectsService = () => new ProjectsService(new Repository<Project>('projects',["id","name","code","is_active","display_order","created_at","updated_at"]));
export const getSupabaseService = () => new SupabaseService();
